
// Example of Exception by using finally block

public class E3 {

    public static void main(String args[]){

        int a , b , c = 0;
 a = 10;
  b = 2;
        System.out.println("before exception..");

    }
}
